cas:
  server-url-prefix: http://server-url
  server-login-url: http://server-url/login
  client-host-url: http://localhost:9100
  validation-type: cas
  authentication-url-patterns:

server:
  port: 9100
