app:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverclassname: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xu?useSSL=false&characterEncoding=utf8&useCompress=true
    username: root
    password: 1234
    maximum-pool-size: 30


spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db.migration